version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-us-east-1-833521035879 --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.yml
